version: '3.7'

services:
  postgrest:
    image: postgrest/postgrest:latest
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PGRST_SERVER_PORT
      - PGRST_DB_SCHEMA
      - PGRST_DB_ANON_ROLE
      - PGRST_JWT_SECRET
    networks:
      net:
        aliases:
          - api
    ports:
      - target: ${PGRST_SERVER_PORT}
        published: ${PUBLISHED_PORT}
        mode: host

networks:
  net:
    name: tajinaste-net
