version: '3.7'

services:
  postgrest:
    image: postgrest/postgrest:${IMAGE_TAG:-latest}
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PGRST_SERVER_PORT
      - PGRST_DB_SCHEMA
      - PGRST_DB_ANON_ROLE
      - PGRST_JWT_SECRET
    networks:
      tajinaste-net:
        aliases:
          - api
      traefik-net:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${PGRST_SERVER_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:tajinaste.${PUBLIC_HOSTNAME};PathPrefixStrip:/api
        traefik.backend: postgrest
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M

networks:
  tajinaste-net:
    name: tajinaste-net

  traefik-net:
    external: true
