version: '3.9'

services:
  tajinaste-api:
    image: ${IMAGE_NAME:-postgrest/postgrest}:${IMAGE_TAG:-latest}
    environment:
      PGRST_DB_URI: ${POSTGRES_PROTOCOL}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}${POSTGRES_PARAMS}
      PGRST_DB_SCHEMAS:
      PGRST_DB_ANON_ROLE:
      PGRST_SERVER_PORT:
      PGRST_JWT_SECRET:
    networks:
      tajinaste-net:
        aliases:
          - ${TAJINASTE_NET_ALIAS:-api}
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.tajinaste-api.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.tajinaste-api.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && PathPrefix(`${TRAEFIK_PATHPREFIX}`)
        traefik.http.middlewares.tajinaste-api-strip-prefix.stripprefix.prefixes: ${TRAEFIK_PATHPREFIX}
        traefik.http.routers.tajinaste-api.middlewares: tajinaste-api-strip-prefix
        traefik.http.services.tajinaste-api.loadbalancer.server.port: ${PGRST_SERVER_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  tajinaste-net:
    name: ${TAJINASTE_NET_NAME:-tajinaste-net}
    driver: ${TAJINASTE_NET_DRIVER:-overlay}
    attachable: ${TAJINASTE_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
